### Project 생성 API
POST http://localhost:8080/api/projects
Content-Type: application/json
X-MEMBER-ID: 100

{
  "name": "Project Mini Dorary"
}

### Project 멤버 추가 API
PUT http://localhost:8080/api/projects/5/members/5
Content-Type: application/json
X-MEMBER-ID: 100

### Project 수정
PATCH http://localhost:8080/api/projects/5
Content-Type: application/json
X-MEMBER-ID: 100

{
  "name": "Project Big Dorary2",
  "status": "CLOSED"
}

### 멤버의 프로젝트 목록 조회
GET http://localhost:8080/api/projects
Content-Type:  application/json
X-MEMBER-ID: 1000




