-- MySQL Script generated by MySQL Workbench
-- Thu May 14 15:52:07 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema mini_dooray_task_api
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mini_dooray_task_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mini_dooray_task_api` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `idtable1` INT NOT NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;

USE `mini_dooray_task_api` ;

-- -----------------------------------------------------
-- Table `mini_dooray_task_api`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_dooray_task_api`.`projects` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `status` ENUM('ACTIVE', 'DORMANT', 'CLOSED') NOT NULL DEFAULT 'ACTIVE',
  `admin_member_id` BIGINT NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  INDEX `idx_projects_admin_member_id` (`admin_member_id` ASC) VISIBLE,
  INDEX `idx_projects_status` (`status` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_dooray_task_api`.`project_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_dooray_task_api`.`project_members` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL,
  `member_id` BIGINT NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_project_members_project_member` (`project_id` ASC, `member_id` ASC) VISIBLE,
  INDEX `idx_project_members_member_id` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_project_members_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `mini_dooray_task_api`.`projects` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_dooray_task_api`.`milestones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_dooray_task_api`.`milestones` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_milestones_project_name` (`project_id` ASC, `name` ASC) VISIBLE,
  CONSTRAINT `fk_milestones_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `mini_dooray_task_api`.`projects` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_dooray_task_api`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_dooray_task_api`.`tasks` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL,
  `milestone_id` BIGINT NULL DEFAULT NULL,
  `title` VARCHAR(200) NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `writer_member_id` BIGINT NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  INDEX `idx_tasks_project_id` (`project_id` ASC) VISIBLE,
  INDEX `idx_tasks_milestone_id` (`milestone_id` ASC) VISIBLE,
  INDEX `idx_tasks_writer_member_id` (`writer_member_id` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `mini_dooray_task_api`.`projects` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_tasks_milestone`
    FOREIGN KEY (`milestone_id`)
    REFERENCES `mini_dooray_task_api`.`milestones` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_dooray_task_api`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_dooray_task_api`.`comments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT NOT NULL,
  `writer_member_id` BIGINT NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  INDEX `idx_comments_task_id` (`task_id` ASC) VISIBLE,
  INDEX `idx_comments_writer_member_id` (`writer_member_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `mini_dooray_task_api`.`tasks` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_dooray_task_api`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_dooray_task_api`.`tags` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_tags_project_name` (`project_id` ASC, `name` ASC) VISIBLE,
  CONSTRAINT `fk_tags_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `mini_dooray_task_api`.`projects` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_dooray_task_api`.`task_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_dooray_task_api`.`task_tags` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT NOT NULL,
  `tag_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_task_tags_task_tag` (`task_id` ASC, `tag_id` ASC) VISIBLE,
  INDEX `idx_task_tags_task_id` (`task_id` ASC) VISIBLE,
  INDEX `idx_task_tags_tag_id` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `fk_task_tags_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `mini_dooray_task_api`.`tasks` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_task_tags_tag`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mini_dooray_task_api`.`tags` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
